### ISSUE TITLE
TXT records?

### ISSUE THREAD

**Issue by jwilkins** [petertodd/unholynames#1]
Curious why you mashed the header into IP addresses instead of using eg TXT records

[jwilkins:~] 1 % host -t TXT 0.hdr.btc.nullops.com
0.hdr.btc.nullops.com descriptive text "000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f"

**Comment by petertodd** [comment]
IPv6 addresses are much easier to retrieve than TXT records, as the latter are often not supported by resolvers (firewalls!) as well as standard system libraries. (need specific DNS resolving libraries)

After all, this is meant to be a somewhat censorship-resistant hack. :)

**Comment by petertodd** [comment]
Though, there's certainly no harm in _also_ supplying TXT records.
